### ISSUE TITLE
[BUG] - Lag when rescuing pawns

### ISSUE THREAD

**Issue by onekum** [IwoRosiak/RimWorldHolsters#1]
**Describe the bug**
Makes my games really laggy when a pawn is rescuing another. Same thing with capturing.

**To Reproduce**
1. Have a pawn attempt to rescue a comrade.

**Screenshots**

**Your modlist/log (very important!):**
[Log posted on github.](https://gist.github.com/HugsLibRecordKeeper/301d2e2926031fc88d3d481594375ee1)

**Additional context**
Search for "Exception drawing Gregory" in the log, it looks like a point of interest where I saw holsters mentioned. Turning holsters off fixes this issue. Probably a mod conflict but I'll post here nonetheless.

**Comment by IwoRosiak** [comment]
Hi there! I pushed fix for that issue :) Let me know if it still persists.
