### ISSUE TITLE
[BUG] - (1.4) FemaleBB constant error spam

### ISSUE THREAD

**Issue by DarknesSeeker** [IwoRosiak/RimWorldHolsters#12]
**Describe the bug**
The console is being spammed with an exception, slowing the game in the process.

**To Reproduce**
Have a pawn with FemaleBB body
Equip any weapon item
Check the Console Log

**Screenshots**
(Due to the constant spam of the in-game log it was impossible to get a full read on the error)
![error](https://github.com/IwoRosiak/Holsters/assets/32309040/0b962285-b56f-48fc-8e69-c7576983b4bf)

**Your modlist/log (very important!):**
It's 300+ mods, and the error especifically is calling out to RimworldHolsters and FemaleBB, si I deemed it not necessary.
Also, the FemaleBB developer [is seemingly already aware of this error](https://steamcommunity.com/workshop/filedetails/discussion/1792668502/1643167006290062249/?ctp=13): 

**Additional context**
As far as I'm aware, this error started appearing just a few days ago.

Thank you for your time and effort.

**Comment by IwoRosiak** [comment]
No problem. Will be fixed this weekend. Thanks for letting me know!

**Comment by IwoRosiak** [comment]
Fixed in the latest patch.
