### ISSUE TITLE
QoL Request

### ISSUE THREAD

**Issue by amaotoUsagi** [IwoRosiak/RimWorldHolsters#3]
Is it possible to make it so that every time I move a weapon to another group, the preview wont get reset to the very first one?
Its becomes quite tedious once you get several weapon mods and some of them are angled at a 45 degree or are placed low in their sprite, so I end up having to move them manually in the custom groups.
Or you could make it that we select the weapons from a dialog box for faster browsing instead of clicking for x-times

**Comment by IwoRosiak** [comment]
Hi there! 
Of course :) the request for this feature popped up a couple of times already, but I keep forgetting about it! I will get on it today :P I have not come up with a way to use a radio box yet, but I will investigate that. I know that if you have 300 weapons in one category, it gets pretty tedious to sort through them.

Do weapons that give you trouble are vanilla or from a mod? I am just wondering if there is a problem there of some sort.

Thanks for the feedback and have a fantastic day :>

**Comment by IwoRosiak** [comment]
The QoL suggestion you made has been added :)

**Comment by amaotoUsagi** [comment]
Thanks for the quick update!
The weapons don't give that much trouble. It just that some weapons are angled at a 45 degrees, mainly to give a bigger weapon sprite without resorting to be Oversized. Such weapons tend to be drawn a lot smaller when holstered, but the preview in the mod settings show them as if theyre held by the pawn.
Like this:
![screenshot40](https://user-images.githubusercontent.com/99400373/156882671-dabbbbc6-13b7-45f1-babb-30336217be4d.png)

**Comment by IwoRosiak** [comment]
I'm not sure if I understand you correctly. 

The problem is that mod settings do not accurately represent the weapon's angle in the game? If yes, then please provide a screenshot of mod settings as well :)

**Comment by amaotoUsagi** [comment]
Ah, my bad. The problem is nothing gamebreaking but its just a size difference due to the Oversized weapons
You can see how it got smaller from the settings and in-game render. This one is from an older version
![Slug](https://user-images.githubusercontent.com/99400373/157048619-08f76e10-3666-48b2-8481-c7437e579b9d.png)
